/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import jodoDaNovinha.AI;
import jodoDaNovinha.Board;
import jodoDaNovinha.Human;
import jodoDaNovinha.Player;
import jodoDaNovinha.Point;

import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.font.TextAttribute;
import java.util.Map;

/**
 *
 * @author nanotech
 */
public class Form0 extends javax.swing.JFrame {
    Board tab;
    Player p1,p2;
    
    public void newGame(){
        if(radio_1p.isSelected()){
            p1=new Human('X');
            p2=new AI('O');
        }else{
            p1=new Human('X');
            p2=new Human('O');
        }
        if((int)Math.random()==0){
            label_turn.setText("Player 1");
        }else{
            label_turn.setText("Player 2");
        }
        tab.clear();
        tab.draw();
    }
    public void PlayerTurn(int i, int j){
        if(!this.getButtons()[i][j].isEnabled()) return;
        if(label_turn.getText().equals("Player 1")){
            Human hu=(Human)p1;
            hu.play(tab, new Point(i,j));
            label_turn.setText("Player 2");
            if(!checkGG())AIturn();
        }else if(radio_2p.isSelected()&&(label_turn.getText().equals("Player 2"))){
            Human hu=(Human)p2;
            hu.play(tab, new Point(i,j));
            label_turn.setText("Player 1");
            checkGG();
        } 
    }
    public void AIturn(){
        if("Player 2".equals(label_turn.getText())){
            if(radio_1p.isSelected()){
                AI ai=(AI)p2;
                ai.play(tab);
                label_turn.setText("Player 1");
                checkGG();
            }
        }
    }
    
    public void endGame(){
        for(int i=0;i<3;i++)
            for(int j=0;j<3;j++)
                this.getButtons()[i][j].setEnabled(false);
        
    }
    
    public boolean checkGG(){
        if(tab.checkCols(p1.getSymbol())||tab.checkDiags(p1.getSymbol())||tab.checkLines(p1.getSymbol())){
            label_turn.setText("P1-WON");
            endGame();
            return true;
        }
        if(tab.checkCols(p2.getSymbol())||tab.checkDiags(p2.getSymbol())||tab.checkLines(p2.getSymbol())){
            label_turn.setText("P2-WON");
            endGame();
            return true;
        }
        boolean condition=true;
        for(int i=0;i<3;i++)
            for(int j=0;j<3;j++)
                if(tab.getMatrix()[i][j]=='-'){condition=false; break;}
        if(condition){
            label_turn.setText("DRAW");
            endGame();
            return true;
        }
        return false;
    }

    public Form0() {
        initComponents();
        radio_1p.setSelected(true);
        this.buttonGroup2.add(radio_1p);
        this.buttonGroup2.add(radio_2p);
        tab = new Board(this);
        this.setTitle("Jogo da Idosa :p");
        
        Font font = url.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        url.setFont(font.deriveFont(attributes));
        url.setCursor(new Cursor(Cursor.HAND_CURSOR));
        url.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
                try{Desktop.getDesktop().browse(new URI(url.getText()));}
                catch (URISyntaxException | IOException ex) {}
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_00 = new javax.swing.JButton();
        btn_01 = new javax.swing.JButton();
        btn_02 = new javax.swing.JButton();
        btn_12 = new javax.swing.JButton();
        btn_11 = new javax.swing.JButton();
        btn_10 = new javax.swing.JButton();
        btn_20 = new javax.swing.JButton();
        btn_21 = new javax.swing.JButton();
        btn_22 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        radio_1p = new javax.swing.JRadioButton();
        radio_2p = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        label_turn = new javax.swing.JLabel();
        url = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 239, 241));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 260));

        btn_00.setText("-");
        btn_00.setFocusable(false);
        btn_00.setMaximumSize(new java.awt.Dimension(50, 50));
        btn_00.setMinimumSize(new java.awt.Dimension(50, 50));
        btn_00.setName(""); // NOI18N
        btn_00.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_00MouseReleased(evt);
            }
        });

        btn_01.setText("-");
        btn_01.setFocusable(false);
        btn_01.setMaximumSize(new java.awt.Dimension(50, 50));
        btn_01.setMinimumSize(new java.awt.Dimension(50, 50));
        btn_01.setName(""); // NOI18N
        btn_01.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_01MouseReleased(evt);
            }
        });
        btn_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_01ActionPerformed(evt);
            }
        });

        btn_02.setText("-");
        btn_02.setFocusable(false);
        btn_02.setMaximumSize(new java.awt.Dimension(50, 50));
        btn_02.setMinimumSize(new java.awt.Dimension(50, 50));
        btn_02.setName(""); // NOI18N
        btn_02.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_02MouseReleased(evt);
            }
        });

        btn_12.setText("-");
        btn_12.setFocusable(false);
        btn_12.setMaximumSize(new java.awt.Dimension(50, 50));
        btn_12.setMinimumSize(new java.awt.Dimension(50, 50));
        btn_12.setName(""); // NOI18N
        btn_12.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_12MouseReleased(evt);
            }
        });

        btn_11.setText("-");
        btn_11.setFocusable(false);
        btn_11.setMaximumSize(new java.awt.Dimension(50, 50));
        btn_11.setMinimumSize(new java.awt.Dimension(50, 50));
        btn_11.setName(""); // NOI18N
        btn_11.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_11MouseReleased(evt);
            }
        });

        btn_10.setText("-");
        btn_10.setFocusable(false);
        btn_10.setMaximumSize(new java.awt.Dimension(50, 50));
        btn_10.setMinimumSize(new java.awt.Dimension(50, 50));
        btn_10.setName(""); // NOI18N
        btn_10.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_10MouseReleased(evt);
            }
        });

        btn_20.setText("-");
        btn_20.setFocusable(false);
        btn_20.setMaximumSize(new java.awt.Dimension(50, 50));
        btn_20.setMinimumSize(new java.awt.Dimension(50, 50));
        btn_20.setName(""); // NOI18N
        btn_20.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_20MouseReleased(evt);
            }
        });

        btn_21.setText("-");
        btn_21.setFocusable(false);
        btn_21.setMaximumSize(new java.awt.Dimension(50, 50));
        btn_21.setMinimumSize(new java.awt.Dimension(50, 50));
        btn_21.setName(""); // NOI18N
        btn_21.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_21MouseReleased(evt);
            }
        });

        btn_22.setText("-");
        btn_22.setFocusable(false);
        btn_22.setMaximumSize(new java.awt.Dimension(50, 50));
        btn_22.setMinimumSize(new java.awt.Dimension(50, 50));
        btn_22.setName(""); // NOI18N
        btn_22.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_22MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("New Game");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        radio_1p.setText("1 Player");
        radio_1p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                radio_1pMouseReleased(evt);
            }
        });
        radio_1p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1pActionPerformed(evt);
            }
        });
        radio_1p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                radio_1pKeyReleased(evt);
            }
        });

        radio_2p.setText("2 Players");
        radio_2p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                radio_2pMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel1.setText("Player Turn:");

        label_turn.setText("null");
        label_turn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                label_turnPropertyChange(evt);
            }
        });

        url.setForeground(new java.awt.Color(64, 0, 255));
        url.setText("https://github.com/thiagofigcosta/");

        jLabel2.setText("by: nanoTech");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(radio_1p)
                            .addComponent(radio_2p)
                            .addComponent(jLabel1)
                            .addComponent(label_turn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(url)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(url)
                    .addComponent(jLabel2))
                .addGap(0, 0, 0))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(radio_1p)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_2p)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_turn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_01ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
       newGame();
    }//GEN-LAST:event_jButton1MouseReleased

    private void btn_00MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_00MouseReleased
       PlayerTurn(0,0);
    }//GEN-LAST:event_btn_00MouseReleased

    private void radio_1pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1pActionPerformed

    private void label_turnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_label_turnPropertyChange
        
    }//GEN-LAST:event_label_turnPropertyChange

    private void radio_1pKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_radio_1pKeyReleased
        
    }//GEN-LAST:event_radio_1pKeyReleased

    private void radio_2pMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_2pMouseReleased
        newGame();
    }//GEN-LAST:event_radio_2pMouseReleased

    private void btn_01MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_01MouseReleased
        PlayerTurn(0,1);
    }//GEN-LAST:event_btn_01MouseReleased

    private void btn_02MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_02MouseReleased
        PlayerTurn(0,2);
    }//GEN-LAST:event_btn_02MouseReleased

    private void btn_10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_10MouseReleased
        PlayerTurn(1,0);
    }//GEN-LAST:event_btn_10MouseReleased

    private void btn_11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_11MouseReleased
        PlayerTurn(1,1);
    }//GEN-LAST:event_btn_11MouseReleased

    private void btn_12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_12MouseReleased
        PlayerTurn(1,2);
    }//GEN-LAST:event_btn_12MouseReleased

    private void btn_20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_20MouseReleased
        PlayerTurn(2,0);
    }//GEN-LAST:event_btn_20MouseReleased

    private void btn_21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_21MouseReleased
        PlayerTurn(2,1);
    }//GEN-LAST:event_btn_21MouseReleased

    private void btn_22MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_22MouseReleased
        PlayerTurn(2,2);
    }//GEN-LAST:event_btn_22MouseReleased

    private void radio_1pMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_1pMouseReleased
        newGame();
    }//GEN-LAST:event_radio_1pMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form0 fmr=new Form0();
                fmr.setVisible(true);
                fmr.newGame();
            }
        });
    }
    
    public javax.swing.JButton[][] getButtons(){
        javax.swing.JButton[][] btns= new javax.swing.JButton[3][3];
        btns[0][0]=btn_00;
        btns[0][1]=btn_01;
        btns[0][2]=btn_02;
        
        btns[1][0]=btn_10;
        btns[1][1]=btn_11;
        btns[1][2]=btn_12;
        
        btns[2][0]=btn_20;
        btns[2][1]=btn_21;
        btns[2][2]=btn_22;
        
        return btns;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_00;
    private javax.swing.JButton btn_01;
    private javax.swing.JButton btn_02;
    private javax.swing.JButton btn_10;
    private javax.swing.JButton btn_11;
    private javax.swing.JButton btn_12;
    private javax.swing.JButton btn_20;
    private javax.swing.JButton btn_21;
    private javax.swing.JButton btn_22;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_turn;
    private javax.swing.JRadioButton radio_1p;
    private javax.swing.JRadioButton radio_2p;
    private javax.swing.JLabel url;
    // End of variables declaration//GEN-END:variables
}
